# Builds the 256-entry SPC700 opcode table from the SNESdev wiki listing.
# Placeholders: {i1} imm byte1, {d1}/{d2} dp byte, {a12} abs (bytes 1,2),
# {r1}/{r2} rel byte, {m12} 13-bit addr + 3-bit bit, {n} opcode>>4, {b} (opcode>>5)
T = [None]*256
def op(code, fmt, length): T[code] = (fmt, length)

alu = {0:"OR", 2:"AND", 4:"EOR", 6:"CMP", 8:"ADC", 0xA:"SBC"}
for hi, name in alu.items():
    op(hi<<4|4,       f"{name} A, {{d1}}", 2)
    op((hi+1)<<4|4,   f"{name} A, {{d1}}+X", 2)
    op(hi<<4|5,       f"{name} A, {{a12}}", 3)
    op((hi+1)<<4|5,   f"{name} A, {{a12}}+X", 3)
    op(hi<<4|6,       f"{name} A, (X)", 1)
    op((hi+1)<<4|6,   f"{name} A, {{a12}}+Y", 3)
    op(hi<<4|7,       f"{name} A, [{{d1}}+X]", 2)
    op((hi+1)<<4|7,   f"{name} A, [{{d1}}]+Y", 2)
    op(hi<<4|8,       f"{name} A, #{{i1}}", 2)
    op((hi+1)<<4|8,   f"{name} {{d2}}, #{{i1}}", 3)
    op(hi<<4|9,       f"{name} {{d2}}, {{d1}}", 3)
    op((hi+1)<<4|9,   f"{name} (X), (Y)", 1)
for hi in range(16):
    op(hi<<4|1, "TCALL {n}", 1)
    op(hi<<4|2, ("SET1" if hi%2==0 else "CLR1") + " {d1}.{b}", 2)
    op(hi<<4|3, ("BBS" if hi%2==0 else "BBC") + " {d1}.{b}, {r2}", 3)
# shifts / inc / dec (xB, xC)
for hi, name in {0:"ASL", 2:"ROL", 4:"LSR", 6:"ROR"}.items():
    op(hi<<4|0xB, f"{name} {{d1}}", 2); op((hi+1)<<4|0xB, f"{name} {{d1}}+X", 2)
    op(hi<<4|0xC, f"{name} {{a12}}", 3); op((hi+1)<<4|0xC, f"{name} A", 1)
op(0x8B,"DEC {d1}",2); op(0x9B,"DEC {d1}+X",2); op(0x8C,"DEC {a12}",3); op(0x9C,"DEC A",1)
op(0xAB,"INC {d1}",2); op(0xBB,"INC {d1}+X",2); op(0xAC,"INC {a12}",3); op(0xBC,"INC A",1)
# xA bit ops
op(0x0A,"OR1 C, {m12}",3); op(0x2A,"OR1 C, /{m12}",3); op(0x4A,"AND1 C, {m12}",3); op(0x6A,"AND1 C, /{m12}",3)
op(0x8A,"EOR1 C, {m12}",3); op(0xAA,"MOV1 C, {m12}",3); op(0xCA,"MOV1 {m12}, C",3); op(0xEA,"NOT1 {m12}",3)
op(0x1A,"DECW {d1}",2); op(0x3A,"INCW {d1}",2); op(0x5A,"CMPW YA, {d1}",2); op(0x7A,"ADDW YA, {d1}",2)
op(0x9A,"SUBW YA, {d1}",2); op(0xBA,"MOVW YA, {d1}",2); op(0xDA,"MOVW {d1}, YA",2); op(0xFA,"MOV {d2}, {d1}",3)
# moves
op(0xE8,"MOV A, #{i1}",2); op(0xE6,"MOV A, (X)",1); op(0xBF,"MOV A, (X)+",1); op(0xE4,"MOV A, {d1}",2)
op(0xF4,"MOV A, {d1}+X",2); op(0xE5,"MOV A, {a12}",3); op(0xF5,"MOV A, {a12}+X",3); op(0xF6,"MOV A, {a12}+Y",3)
op(0xE7,"MOV A, [{d1}+X]",2); op(0xF7,"MOV A, [{d1}]+Y",2)
op(0xCD,"MOV X, #{i1}",2); op(0xF8,"MOV X, {d1}",2); op(0xF9,"MOV X, {d1}+Y",2); op(0xE9,"MOV X, {a12}",3)
op(0x8D,"MOV Y, #{i1}",2); op(0xEB,"MOV Y, {d1}",2); op(0xFB,"MOV Y, {d1}+X",2); op(0xEC,"MOV Y, {a12}",3)
op(0xC6,"MOV (X), A",1); op(0xAF,"MOV (X)+, A",1); op(0xC4,"MOV {d1}, A",2); op(0xD4,"MOV {d1}+X, A",2)
op(0xC5,"MOV {a12}, A",3); op(0xD5,"MOV {a12}+X, A",3); op(0xD6,"MOV {a12}+Y, A",3)
op(0xC7,"MOV [{d1}+X], A",2); op(0xD7,"MOV [{d1}]+Y, A",2)
op(0xD8,"MOV {d1}, X",2); op(0xD9,"MOV {d1}+Y, X",2); op(0xC9,"MOV {a12}, X",3)
op(0xCB,"MOV {d1}, Y",2); op(0xDB,"MOV {d1}+X, Y",2); op(0xCC,"MOV {a12}, Y",3)
op(0x7D,"MOV A, X",1); op(0xDD,"MOV A, Y",1); op(0x5D,"MOV X, A",1); op(0xFD,"MOV Y, A",1)
op(0x9D,"MOV X, SP",1); op(0xBD,"MOV SP, X",1); op(0x8F,"MOV {d2}, #{i1}",3)
# compares X/Y
op(0xC8,"CMP X, #{i1}",2); op(0x3E,"CMP X, {d1}",2); op(0x1E,"CMP X, {a12}",3)
op(0xAD,"CMP Y, #{i1}",2); op(0x7E,"CMP Y, {d1}",2); op(0x5E,"CMP Y, {a12}",3)
# inc/dec regs, misc
op(0x3D,"INC X",1); op(0xFC,"INC Y",1); op(0x1D,"DEC X",1); op(0xDC,"DEC Y",1); op(0x9F,"XCN A",1)
op(0xCF,"MUL YA",1); op(0x9E,"DIV YA, X",1); op(0xDF,"DAA A",1); op(0xBE,"DAS A",1)
# branches
op(0x2F,"BRA {r1}",2); op(0xF0,"BEQ {r1}",2); op(0xD0,"BNE {r1}",2); op(0xB0,"BCS {r1}",2); op(0x90,"BCC {r1}",2)
op(0x70,"BVS {r1}",2); op(0x50,"BVC {r1}",2); op(0x30,"BMI {r1}",2); op(0x10,"BPL {r1}",2)
op(0x2E,"CBNE {d1}, {r2}",3); op(0xDE,"CBNE {d1}+X, {r2}",3); op(0x6E,"DBNZ {d1}, {r2}",3); op(0xFE,"DBNZ Y, {r1}",2)
op(0x5F,"JMP {a12}",3); op(0x1F,"JMP [{a12}+X]",3)
op(0x3F,"CALL {a12}",3); op(0x4F,"PCALL {i1}",2); op(0x0F,"BRK",1); op(0x6F,"RET",1); op(0x7F,"RETI",1)
op(0x2D,"PUSH A",1); op(0x4D,"PUSH X",1); op(0x6D,"PUSH Y",1); op(0x0D,"PUSH PSW",1)
op(0xAE,"POP A",1); op(0xCE,"POP X",1); op(0xEE,"POP Y",1); op(0x8E,"POP PSW",1)
op(0x0E,"TSET1 {a12}",3); op(0x4E,"TCLR1 {a12}",3)
op(0x60,"CLRC",1); op(0x80,"SETC",1); op(0xED,"NOTC",1); op(0xE0,"CLRV",1); op(0x20,"CLRP",1); op(0x40,"SETP",1)
op(0xA0,"EI",1); op(0xC0,"DI",1); op(0x00,"NOP",1); op(0xEF,"SLEEP",1); op(0xFF,"STOP",1)
missing = [i for i,t in enumerate(T) if t is None]
assert not missing, [hex(m) for m in missing]
lines = []
for i,(f,l) in enumerate(T):
    lines.append(f'    {{"{f}", {l}}},  // {i:02X}')
open(__import__("os").path.join(__import__("os").path.dirname(__file__), "..", "src", "spc700_table.inc"), "w").write(
 "// Generated by tools/gen_spc700_table.py from the SNESdev wiki SPC700 listing (CC0).\n"
 "// {i1} imm, {d1}/{d2} dp, {a12} abs, {r1}/{r2} rel, {m12} addr.bit, {n} opcode>>4, {b} opcode>>5\n"
 + "\n".join(lines) + "\n")
print("ok", len(T))
