# Writes ${OUT} (version.cpp) from the git state of ${SRC}: the built commit,
# its branch and the last commits as the changelog. Runs on every build and
# only rewrites the file when something changed, so nothing relinks needlessly.
find_package(Git QUIET)
string(ASCII 30 RS)
string(ASCII 31 US)
set(commit "")
set(branch "")
set(date "")
set(time 0)
set(remote "")
set(tag "")
set(since_tag 0)
set(log "")
if(GIT_EXECUTABLE AND EXISTS "${SRC}/.git")
    macro(git_out var)
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC} ${ARGN} OUTPUT_VARIABLE ${var} OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
        if(NOT rc EQUAL 0)
            set(${var} "")
        endif()
    endmacro()
    git_out(commit rev-parse HEAD)
    git_out(branch rev-parse --abbrev-ref HEAD)
    git_out(date log -1 --format=%as)
    git_out(time log -1 --format=%at)
    git_out(remote remote get-url origin)
    # v0.4.0-3-gabc1234: the release tag this build follows and how far behind it is
    git_out(describe describe --tags --match "v[0-9]*" --long)
    if(describe MATCHES "^(v[0-9][^-]*)-([0-9]+)-g[0-9a-f]+$")
        set(tag "${CMAKE_MATCH_1}")
        set(since_tag "${CMAKE_MATCH_2}")
    endif()
    git_out(log log -n 40 --format=%H${US}%as${US}%at${US}%s${US}%b${RS})
    git_out(dirty status --porcelain --untracked-files=no)
    if(dirty)
        set(commit "${commit}+")
    endif()
endif()
if(NOT time MATCHES "^[0-9]+$")
    set(time 0)
endif()
if(branch STREQUAL "HEAD" OR branch STREQUAL "")
    set(branch "master")
endif()

set(D "~boom~")   # raw string delimiter, never in a commit message
set(entries "")
set(count 0)
set(rest "${log}")
while(TRUE)
    string(FIND "${rest}" "${RS}" pos)
    if(pos LESS 0)
        break()
    endif()
    string(SUBSTRING "${rest}" 0 ${pos} rec)
    math(EXPR pos "${pos} + 1")
    string(SUBSTRING "${rest}" ${pos} -1 rest)
    string(STRIP "${rec}" rec)
    if(rec STREQUAL "")
        continue()
    endif()
    # Split by hand: list() would treat semicolons in a message as separators.
    foreach(name hash date time subject body)
        string(FIND "${rec}" "${US}" p)
        if(p LESS 0)
            set(f_${name} "${rec}")
            set(rec "")
        else()
            string(SUBSTRING "${rec}" 0 ${p} f_${name})
            math(EXPR p "${p} + 1")
            string(SUBSTRING "${rec}" ${p} -1 rec)
        endif()
    endforeach()
    string(STRIP "${f_body}" f_body)
    if(NOT f_time MATCHES "^[0-9]+$")
        set(f_time 0)
    endif()
    string(APPEND entries "    {\"${f_hash}\", \"${f_date}\", ${f_time}, R\"${D}(${f_subject})${D}\", R\"${D}(${f_body})${D}\"},\n")
    math(EXPR count "${count} + 1")
endwhile()

set(content "// Generated by cmake/version.cmake on every build. Do not edit.
#include \"version.hpp\"

namespace {
const Commit kLog[] = {
${entries}    {nullptr, nullptr, 0, nullptr, nullptr},
};
const BuildInfo kInfo = {
    \"${VERSION}\",
    \"${commit}\",
    \"${branch}\",
    \"${date}\",
    ${time},
    \"${tag}\",
    ${since_tag},
    R\"${D}(${remote})${D}\",
    R\"${D}(${SRC})${D}\",
    R\"${D}(${BIN})${D}\",
    R\"${D}(${CMAKE_EXE})${D}\",
    R\"${D}(${GENERATOR})${D}\",
    \"${BUILD_TYPE}\",
    kLog,
    ${count},
};
}

const BuildInfo& build_info() { return kInfo; }
")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
